import type { CapacitorConfig } from "@capacitor/cli";

/**
 * Capacitor config — Phase 2 native shell for the CRIS Golf Program app.
 *
 * The web layer is the SAME Next.js static export that ships to Vercel:
 *   webDir = "out"  (produced by `npm run build`).
 *
 * Workflow:
 *   npm run build && npx cap sync ios
 *
 * The iOS native project (ios/) is NOT committed — it is generated by the CI
 * build (or `npx cap add ios` on a Mac) from this config. See TESTFLIGHT.md.
 */
const config: CapacitorConfig = {
  appId: "th.ac.cris.golf",
  appName: "CRIS Golf Program",
  webDir: "out",
};

export default config;
