import type { Metadata, Viewport } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { HtmlLangSync } from "@/components/HtmlLangSync";
import { PwaRegister } from "@/components/PwaRegister";
import { BRAND_NAVY } from "@/config/theme";

/**
 * iOS startup-image splash entries — 1G follow-up.
 *
 * iOS ignores the web manifest for launch screens; it requires one PNG per
 * device resolution served via <link rel="apple-touch-startup-image"> with a
 * matching `media` query (device-width/height + -webkit-device-pixel-ratio +
 * orientation).  Without these tags the installed PWA shows a plain white
 * launch screen on iOS.
 *
 * Assets live in public/icons/splash/ and are generated by:
 *   node scripts/generate-splash.mjs
 *
 * Splash art is the real CRIS Golf crest (assets/brand/app-logo.jpg). To change
 * it, replace that source image and re-run scripts/generate-splash.mjs, then
 * `npm run build`. No changes to this layout file are required — the hrefs are
 * stable.
 *
 * Media-query format required by iOS Safari:
 *   (device-width: Wpx) and (device-height: Hpx)
 *   and (-webkit-device-pixel-ratio: R)
 *   and (orientation: portrait|landscape)
 *
 * The Next.js Metadata API does not expose apple-touch-startup-image, so these
 * are raw <link> elements rendered from a static array below (same approach
 * used by most production PWAs targeting iOS).
 *
 * Background colour: BRAND_NAVY (#0c4a6e) — matches the app icon so the
 * launch transition feels seamless.  The manifest.ts background_color (#ffffff)
 * is the Android convention; iOS uses the icon background, not that field.
 */

/**
 * One entry per device × orientation.
 * Generated by scripts/generate-splash.mjs — do not hand-edit.
 * To regenerate: node scripts/generate-splash.mjs  (outputs to public/icons/splash/)
 */
const IOS_SPLASH_LINKS: { href: string; media: string }[] = [
  // ── iPhone SE 1st gen / iPod touch 7 — 320×568 @2× ──────────────────────
  { href: "/icons/splash/splash-iphone-se1-portrait.png",      media: "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { href: "/icons/splash/splash-iphone-se1-landscape.png",     media: "(device-width: 568px) and (device-height: 320px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // ── iPhone 8 / 7 / 6s / 6 / SE 2nd–3rd gen — 375×667 @2× ───────────────
  { href: "/icons/splash/splash-iphone-8-portrait.png",        media: "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { href: "/icons/splash/splash-iphone-8-landscape.png",       media: "(device-width: 667px) and (device-height: 375px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // ── iPhone 8 Plus / 7 Plus / 6s Plus — 414×736 @3× ──────────────────────
  { href: "/icons/splash/splash-iphone-8-plus-portrait.png",   media: "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  { href: "/icons/splash/splash-iphone-8-plus-landscape.png",  media: "(device-width: 736px) and (device-height: 414px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" },
  // ── iPhone X / XS / 11 Pro / 12 mini / 13 mini — 375×812 @3× ────────────
  { href: "/icons/splash/splash-iphone-x-portrait.png",        media: "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  { href: "/icons/splash/splash-iphone-x-landscape.png",       media: "(device-width: 812px) and (device-height: 375px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" },
  // ── iPhone XS Max / 11 Pro Max — 414×896 @3× ─────────────────────────────
  { href: "/icons/splash/splash-iphone-xs-max-portrait.png",   media: "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  { href: "/icons/splash/splash-iphone-xs-max-landscape.png",  media: "(device-width: 896px) and (device-height: 414px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" },
  // ── iPhone XR / 11 — 414×896 @2× ─────────────────────────────────────────
  { href: "/icons/splash/splash-iphone-xr-portrait.png",       media: "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { href: "/icons/splash/splash-iphone-xr-landscape.png",      media: "(device-width: 896px) and (device-height: 414px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // ── iPhone 12 / 12 Pro / 13 / 13 Pro / 14 / 15 / 16 — 390×844 @3× ───────
  { href: "/icons/splash/splash-iphone-12-portrait.png",       media: "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  { href: "/icons/splash/splash-iphone-12-landscape.png",      media: "(device-width: 844px) and (device-height: 390px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" },
  // ── iPhone 12 Pro Max / 13 Pro Max / 14 Plus — 428×926 @3× ──────────────
  { href: "/icons/splash/splash-iphone-12-max-portrait.png",   media: "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  { href: "/icons/splash/splash-iphone-12-max-landscape.png",  media: "(device-width: 926px) and (device-height: 428px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" },
  // ── iPhone 14 Pro / 15 Pro / 16 Pro — 393×852 @3× ───────────────────────
  { href: "/icons/splash/splash-iphone-14-pro-portrait.png",   media: "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  { href: "/icons/splash/splash-iphone-14-pro-landscape.png",  media: "(device-width: 852px) and (device-height: 393px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" },
  // ── iPhone 14 Pro Max / 15 Plus / 16 Plus — 430×932 @3× ─────────────────
  { href: "/icons/splash/splash-iphone-14-pro-max-portrait.png",  media: "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  { href: "/icons/splash/splash-iphone-14-pro-max-landscape.png", media: "(device-width: 932px) and (device-height: 430px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" },
  // ── iPhone 15 Pro Max / 16 Pro Max — 440×956 @3× ─────────────────────────
  { href: "/icons/splash/splash-iphone-15-pro-max-portrait.png",  media: "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  { href: "/icons/splash/splash-iphone-15-pro-max-landscape.png", media: "(device-width: 956px) and (device-height: 440px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" },
  // ── iPad 9.7" / mini 4 / Air 2 — 768×1024 @2× ───────────────────────────
  { href: "/icons/splash/splash-ipad-97-portrait.png",         media: "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { href: "/icons/splash/splash-ipad-97-landscape.png",        media: "(device-width: 1024px) and (device-height: 768px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // ── iPad Pro 10.5" / Air 3 — 834×1112 @2× ───────────────────────────────
  { href: "/icons/splash/splash-ipad-10-5-portrait.png",       media: "(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { href: "/icons/splash/splash-ipad-10-5-landscape.png",      media: "(device-width: 1112px) and (device-height: 834px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // ── iPad Pro 11" (all gens) / Air 4th–5th gen — 834×1194 @2× ────────────
  { href: "/icons/splash/splash-ipad-11-portrait.png",         media: "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { href: "/icons/splash/splash-ipad-11-landscape.png",        media: "(device-width: 1194px) and (device-height: 834px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // ── iPad Pro 12.9" (2nd gen+) — 1024×1366 @2× ───────────────────────────
  { href: "/icons/splash/splash-ipad-12-9-portrait.png",       media: "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { href: "/icons/splash/splash-ipad-12-9-landscape.png",      media: "(device-width: 1366px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // ── iPad 10th gen — 820×1180 @2× ─────────────────────────────────────────
  { href: "/icons/splash/splash-ipad-10th-portrait.png",       media: "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { href: "/icons/splash/splash-ipad-10th-landscape.png",      media: "(device-width: 1180px) and (device-height: 820px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // ── iPad mini 6th gen — 744×1133 @2× ────────────────────────────────────
  { href: "/icons/splash/splash-ipad-mini-6-portrait.png",     media: "(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { href: "/icons/splash/splash-ipad-mini-6-landscape.png",    media: "(device-width: 1133px) and (device-height: 744px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Root metadata — used for the "/" redirect page only.
 * Locale-specific titles/descriptions come from [locale]/layout.tsx.
 *
 * Subphase 1F additions:
 *   - manifest: Next.js App Router wires this automatically from app/manifest.ts
 *   - themeColor: in generateViewport (Next.js 16 requirement — not in metadata)
 *   - appleWebApp: improves iOS "Add to Home Screen" experience (§4 PWA notes)
 *   - icons: apple-touch-icon 180×180 for iOS home-screen icon
 *
 * Note (§4): iOS PWA via "Add to Home Screen" (Safari share sheet) is the
 * iOS install path for the PWA.  The App Store iOS build is Phase 2 only.
 * These meta tags maximise the quality of the iOS "Add to Home Screen" path.
 * The apple-touch-icon is the real CRIS Golf logo (public/icons/apple-touch-icon.png).
 */
export const metadata: Metadata = {
  title: "CRIS Golf Program",
  description: "Chiang Rai International School – Golf Program",
  // manifest is auto-linked by Next.js from app/manifest.ts
  manifest: "/manifest.webmanifest",
  // Apple PWA meta tags — improve "Add to Home Screen" on iOS Safari
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "CRIS Golf",
  },
  // Apple touch icon — shown on iOS home screen
  icons: {
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180" }],
  },
};

/**
 * Viewport export — Next.js 16 requires themeColor here, not in metadata.
 * Sets the browser chrome colour to the CRIS brand navy on Android/Chrome,
 * matching the AppHeader background.
 */
export const viewport: Viewport = {
  themeColor: BRAND_NAVY,
};

/**
 * Root layout — the single required Next.js App Router root layout.
 *
 * Responsibilities:
 *   - Provides the <html> and <body> elements (required here, not in nested layouts).
 *   - Loads the Geist font variable.
 *   - Renders HtmlLangSync which updates <html lang> client-side to match
 *     the active locale URL segment (so screen-readers and translators see
 *     the correct language code after hydration).
 *   - Renders PwaRegister (subphase 1F) which registers the service worker
 *     client-side after page load.
 *
 * The app shell (header, tabs, footer) lives in app/[locale]/layout.tsx
 * and is not rendered for the root "/" redirect page.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactElement {
  return (
    /*
     * lang defaults to "en" at render time; HtmlLangSync updates it
     * client-side to match the active [locale] URL segment.
     */
    <html
      lang="en"
      dir="ltr"
      className={`${geistSans.variable} h-full antialiased`}
    >
      {/*
       * iOS startup-image splash tags (1G follow-up).
       * Injected via a <head> element here because Next.js Metadata API does
       * not expose apple-touch-startup-image.  Raw <link> in <head> is the
       * standard pattern used by production PWAs for iOS splash support.
       * The IOS_SPLASH_LINKS array above drives these — do not edit inline.
       */}
      <head>
        {IOS_SPLASH_LINKS.map((entry) => (
          <link
            key={entry.href}
            rel="apple-touch-startup-image"
            media={entry.media}
            href={entry.href}
          />
        ))}
      </head>
      <body className="flex min-h-full flex-col bg-white text-slate-900">
        {/* Syncs <html lang> to the active locale from the URL */}
        <HtmlLangSync />
        {/* Registers the service worker for PWA installability + offline (1F) */}
        <PwaRegister />
        {children}
      </body>
    </html>
  );
}
